import styles from './style.module.css'

export const metadata = {
    title: "POVS",
    description: "Generated by create next app",
};

export default function Page() {
    return <main>
        <div className="groogle-text">
            <span>OWCS Archive</span>
        </div>

        
    </main>
}