import styles from './twab.module.css'

export const metadata = {
    title: "TWAB Search",
    description: "Generated by create next app",
  };

export default function Page() {
    return <main>
            <div className="top-bar">
                <a id="total-twabs">Twabs Loaded: {1}</a>
                <a> | </a>
                <a id="recent" style={{alignItems: "end"}}>Recent: {1}</a>
                <a className="home" href="/">Home</a>
            </div>

            <div className="groogle-text" >
                <span>Twab Search</span>
            </div>

            <div className={styles.searchbox}>
                <div className={styles.searchbar}>
                    <img id={styles.searchsymbol} src="/Search.svg" onClick={load_search()}/>
                    <input id={styles.search} autoComplete="off"/>
                </div>
            </div>
        </main>
}

export function load_search() {
    console.log("yo");
}