import styles from './twab.module.css'
import Link from "next/link";

export const metadata = {
    title: "TWAB Search",
    description: "Generated by create next app",
  };

export default function Page() {
    return <main>
            <div className="top-bar">
                <a id="total-twabs">Twabs Loaded: {1}</a>
                <a> | </a>
                <a id="recent" style={{alignItems: "end"}}>Recent: {1}</a>
                <Link className="home" href={"/"}>Home</Link>
            </div>

            <div className="groogle-text" >
                <span>Twab Search</span>
            </div>

            <div className={styles.searchbox}>
                <div className={styles.searchbar}>
                    <img id={styles.searchsymbol} src="/Search.svg" onClick={load_search()} alt={"Search Icon"}/>
                    <input id={styles.search} autoComplete="off"/>
                </div>
            </div>

            <div className={styles.resultscontainer}>

            </div>
        </main>
}

export function load_search() {
    console.log("yo");
}