import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Groogle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <div className="footer">
          <a>Created by PlateOfSuki</a>
          <a>   |   </a>
          <a href="https://www.termsfeed.com/live/10efd1b2-8dfb-4439-9e36-8b095bbdf6f3">Privacy Policy</a>
        </div>
      </body>
    </html>
  );
}
