import styles from './style.module.css';
import { Archivo_Black} from "next/font/google";
import OceHeader from "@/app/(frontend)/ocetv/UI/header";
import Results from "@/app/(frontend)/ocetv/UI/ResultsList";


export const metadata = {
    title: "OCE Overwatch TV",
    description: "Generated by create next app",
};

const font = Archivo_Black({
    weight: '400',
    subsets: ['latin']
});

export default function Page() {
    return <main className={font.className}>
        <OceHeader />
        <div className={styles.background}>
            <Results />
            <div className={styles.mainContent}>

            </div>
            <Results />
        </div>
    </main>
}